backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

media_folder: static/img
public_folder: static/img

collections:
  - name: 'docs'
    label: 'Docs'
    label_singular: 'Doc'
    folder: 'docs'
    extension: md
    widget: list
    create: true
    slug: {{slug}}
    fields:
      - {label: 'Name', name: 'name'}
      - {label: 'Menu', name: 'menu', required: false}
      - {label: 'Body', name: 'body', widget: 'markdown'}
