backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: static/img

collections:
  - name: 'docs'
    label: 'Docs'
    label_singular: 'Doc'
    folder: 'src/pages/docs'
    extension: md
    widget: list
    create: true
    fields:
      - {label: 'Name', name: 'name'}
      - {label: 'Menu', name: 'menu', required: false}
      - {label: 'Route', name: 'route'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
